### ISSUE TITLE
Error: Cannot find module 'puppeteer/internal/node/install.js'

### ISSUE THREAD

**Issue by UltraNote** [webnexus-uk/ChatBot-OpenAI#1]
Node v18.13.0
npm 8.19.3

npm ERR! Error: Cannot find module 'puppeteer/internal/node/install.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:692:17)
npm ERR!     at require (internal/modules/cjs/helpers.js:25:18)
npm ERR!     at Object.<anonymous> (/home/mahmoud/ChatBot-OpenAI/api/node_modules/puppeteer/install.js:38:27)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

npm ERR! A complete log of this run can be found in:

**Comment by UltraNote** [comment]
Solved the issue by updating npm to v 9.2.0
